### ISSUE TITLE
Doesn't work anymore with TB >=78

### ISSUE THREAD

**Issue by ojaksch** [tipichris/TBDialOut#16]
On my test/playground VM, running win8.1, TB updated itself to v78.0.1 and TBDialout doesn't work anymore. TBD is available and active in TB's _Tools/Addons_ menu, but _Tools/Addon Settings_ is gone just as the dial button and dialling capabilities in addressbook.

Maybe we need another fixup and test run, before everybody else is getting TB78.

**Comment by susobaco** [comment]
Same problem in debian buster.

**Comment by tipichris** [comment]
An initial attempt at compatibility with TB 78 is now available at https://www.oak-wood.co.uk/downloads/tbdialout/tbdialout-2.0.0pre1.xpi. Please test it let me know of any issues. I won't be routinely using TB 78 for a while yet so will be unable to test extensively myself.

**Comment by ovari** [comment]
Please add the `hu` locale to https://www.oak-wood.co.uk/downloads/tbdialout/tbdialout-2.0.0pre1.xpi? Thank you

**Comment by ojaksch** [comment]
Did some first tests now at local/private site and it's working flawlessy. Congrats and many thanks!
But one question: Wasn't the phone numbers at the lower half of the adressbook clickable in older versions of TBD? They aren't (now).

![Screenshot_20201130_074953](https://user-images.githubusercontent.com/17717333/100577805-45805200-32e1-11eb-8a2c-ad699b0214b5.png)

**Comment by tipichris** [comment]
They did, and they still are on my test machine. It appears to be a localisation issue. I had to completely change the way the links were done, which means the strings defining the tool tips now need to be stored in a different way. I only made the move for English so far. This is basically because ultimately all the localisation has to be changed, so I was going to leave it until I do the whole lot. I assumed the links would still work, but have English tooltips. Evidently not :(

Just to confirm this, could you try changing your locale to en and seeing if they work. May have to be en-GB.

The good news is I actually started, and got quite a long way through migrating the whole lot to the new i18n system yesterday.

**Comment by tipichris** [comment]
@ovari Thanks for the Hungarian translations. Sorry I didn't manage to incorporate them for 2.0.0pre1. There are some issues with the localisation in 2.0.0 (see comment above) which I'm working on, and Hungarian will be in the next release.

BTW, is there a particular reason to give the extension a different name in Hungarian? In all other languages, even Chineses, it retains its original name of 'TBDialout'.

**Comment by ojaksch** [comment]
> They did, and they still are on my test machine. It appears to be a localisation issue. I had to completely change the way the links were done, which means the strings defining the tool tips now need to be stored in a different way. I only made the move for English so far. This is basically because ultimately all the localisation has to be changed, so I was going to leave it until I do the whole lot. I assumed the links would still work, but have English tooltips. Evidently not :(
> 
> Just to confirm this, could you try changing your locale to en and seeing if they work. May have to be en-GB.
> 
> The good news is I actually started, and got quite a long way through migrating the whole lot to the new i18n system yesterday.

Hehe, when changing locale to en-GB tooltips and clickable numbers are working again.
Well, easy task...I added your tooltips my de locale in tbdialout.properties, changed back to german language and voila, tooltips and clickable numbers are working there also.

`cellTooltip=Diesen Kontakt auf seiner mobilen Nummer anrufen`
`homeTooltip=Diesen Kontakt auf seiner privaten Nummer anrufen`
`workTooltip=Diesen Kontakt auf seiner dienstlichen Nummer anrufen`

**Comment by tipichris** [comment]
The old ones are shorter still (they were in the DTD file)
```
Rufe diese Privat-Nr.
Rufe diese Dienstlich-Nr.
Rufe diese Mobil-Nr.
```
All of these messages will be moved to the messages.json file in _locales in the next release.

**Comment by ovari** [comment]
> BTW, is there a particular reason to give the extension a different name in Hungarian? In all other languages, even Chineses, it retains its original name of 'TBDialout'.

[Névjegyzék (CardBook)](https://addons.thunderbird.net/hu/thunderbird/addon/cardbook/)
[Küldés később](https://addons.thunderbird.net/hu/thunderbird/addon/send-later-3/)
[Üzenet átirányítás (Mail Redirect)](https://addons.thunderbird.net/hu/thunderbird/addon/mailredirect/)
[Tömörített fejléc (CompactHeader)](https://addons.thunderbird.net/hu/thunderbird/addon/compactheader/)
[DKIM ellenőrző (DKIM Verifier)](https://addons.thunderbird.net/hu/thunderbird/addon/dkim-verifier/)
[Nyelvtan-ellenőrzés (Grammar Checker)](https://addons.thunderbird.net/hu/thunderbird/addon/grammar-checker/)
[Helyi mappák (LocalFolders)](https://addons.thunderbird.net/hu/thunderbird/addon/localfolder/)
[MutasdMeg! (LookOut)](https://addons.thunderbird.net/hu/thunderbird/addon/lookout-fix-version/)
[Gyorsszöveg (Quicktext)](https://addons.thunderbird.net/hu/thunderbird/addon/quicktext/)

**Comment by tipichris** [comment]
[Version 2.0.0pre2](https://www.oak-wood.co.uk/downloads/tbdialout/tbdialout-2.0.0pre2.xpi) is now available for testing. The i18n has been completely rewritten, and the links should now work in languages other than English. @ovari , this release includes your Hungarian translation.

Please let me know how you get on. I'll look to submitting a release of version 2.0.0 to addons.thunderbird.net shortly.

**Comment by tipichris** [comment]
I have submitted version 2.0.0, compatible with TB78, to addons.thunderbird.net. It can also be [downloaded from here](https://www.oak-wood.co.uk/downloads/tbdialout/tbdialout-2.0.0.xpi).

As we seem to have a version working with TB78 I'll close this issue, but please do open another if you find any problems.

**Comment by ovari** [comment]
@tipichris can you please enable the statistics to be public?
https://addons.thunderbird.net/thunderbird/addon/tbdialout/statistics/

Thank you
